# Use root/example as user/password credentials
version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017  
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: hacho
      #MONGO_INITDB_ROOT_PASSWORD: 123123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    #environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: hacho
      #ME_CONFIG_MONGODB_ADMINPASSWORD: 123123
